rename alert severity name "minor" to "error"
cybozu-go/neco-apps pull request #1163
Opened 2021-02-08 07:33 UTC by umezawatakeshi

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

2021-02-08 09:24 UTC, ymmt2005 requested changes

2021-02-08 09:24 UTC, ymmt2005 commented on monitoring/base/prometheus/alert_rules/metallb.yaml
> +            unless on(node) kube_node_spec_taint{key="node.kubernetes.io/unreachable",effect="NoExecute"}
DaemonSet has a toleration for `node.kubernetes.io/unreachable`.
Why don't you use CKE's taints? https://github.com/cybozu-go/cke/blob/main/docs/sabakan-integration.md

2021-02-08 09:24 UTC, ymmt2005 commented on monitoring/base/victoriametrics/rules/metallb-alertrule.yaml
> +              unless on(node) kube_node_spec_taint{key="node.kubernetes.io/unreachable",effect="NoExecute"}
ditto

2021-02-08 09:24 UTC, ymmt2005 commented on monitoring/base/prometheus/alert_rules/network-policy.yaml
> +            unless on(node) kube_node_spec_taint{key="node.kubernetes.io/unreachable",effect="NoExecute"}
ditto

2021-02-08 09:24 UTC, ymmt2005 commented on monitoring/base/victoriametrics/rules/network-policy-alertrule.yaml
> +              unless on(node) kube_node_spec_taint{key="node.kubernetes.io/unreachable",effect="NoExecute"}
ditto

2021-02-09 02:46 UTC, morimoto-cybozu commented on monitoring/base/prometheus/alert_rules/etcd.yaml
> +      - alert: BootserverEtcdMissing
Is it common practice to set 2 alerts with the same name while differentiating their severity?

2021-02-09 02:55 UTC, umezawatakeshi commented on monitoring/base/prometheus/alert_rules/metallb.yaml
> +            unless on(node) kube_node_spec_taint{key="node.kubernetes.io/unreachable",effect="NoExecute"}
Unfortunately, `cke.cybozu.com/state` taint is not added during all-servers reboot due to CKE's problem. We cannot use it for unreachable detection currently.

Even if DaemonSet has a toleration for `node.kubernetes.io/unreachable`, this is not a problem. This alert expression uses the taint just for alert suppression.

2021-02-09 03:04 UTC, ymmt2005 commented on monitoring/base/prometheus/alert_rules/metallb.yaml
> +            unless on(node) kube_node_spec_taint{key="node.kubernetes.io/unreachable",effect="NoExecute"}
Alright.

2021-02-09 03:05 UTC, ymmt2005 submitted a review, later dismissed

2021-02-09 03:10 UTC, umezawatakeshi commented on monitoring/base/prometheus/alert_rules/etcd.yaml
> +      - alert: BootserverEtcdMissing
Yes. Alertmanager can inhibit alerts with lower severity. See inhibit_rules in [Alertmanager Example](https://github.com/prometheus/alertmanager/blob/master/README.md#example).

2021-02-09 04:09 UTC, ymmt2005 submitted a review, later dismissed
LGTM

2021-02-09 22:59 UTC, ymmt2005 approved these changes
LGTM

2021-02-09 22:59 UTC, merged