[ci skip] PoC teleport node Pod.
cybozu-go/neco-apps pull request #1302
Opened 2021-03-08 09:23 UTC by kfyharukz

Signed-off-by: Kazuhito MATSUDA <kazuhito.matuda@gmail.com>

2021-03-10 07:46 UTC, morimoto-cybozu requested changes

2021-03-10 07:46 UTC, morimoto-cybozu commented on teleport/base/apps/alertmanager.yaml
> +      serviceAccountName: teleport
This file is not referred by kustomization.yaml.
It seems to me that this was revived accidentally.

2021-03-10 07:46 UTC, morimoto-cybozu commented on secrets/base/teleport/teleport.yaml
> +    severity: DEBUG
I'm worried that this could produce too many logs.

2021-03-10 07:46 UTC, morimoto-cybozu commented on teleport/base/nodes/maneki.yaml
> +          secretName: teleport-node-secret-20210309
```suggestion
          secretName: teleport-general-secret-20210309
```

2021-03-10 07:50 UTC, kfyharukz commented on secrets/base/teleport/teleport.yaml
> +    severity: DEBUG
This configuration only for dctest, so I think DEBUG logs are useful if something wrong in CI.

2021-03-10 07:50 UTC, kfyharukz commented on teleport/base/nodes/maneki.yaml
> +          secretName: teleport-node-secret-20210309
🙏

2021-03-10 07:53 UTC, kfyharukz commented on teleport/base/apps/alertmanager.yaml
> +      serviceAccountName: teleport
🙏

2021-03-10 08:12 UTC, morimoto-cybozu approved these changes
LGTM
The branch name is confusing:-D

2021-03-11 05:52 UTC, morimoto-cybozu approved these changes

2021-03-17 01:31 UTC, morimoto-cybozu approved these changes
LGTM

2021-03-17 01:33 UTC, merged