Revert Teleport test to run on the test host
cybozu-go/neco-apps pull request #1345
Opened 2021-03-25 03:10 UTC by ysksuzuki

Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>

2021-03-25 08:35 UTC, tapih requested changes

2021-03-25 08:35 UTC, tapih commented on test/teleport_test.go
> +	"io/ioutil"
`io/ioutil` is deprecated in Go [1.16](https://golang.org/doc/go1.16#ioutil). Please use `os` instead.

2021-03-25 08:35 UTC, tapih commented on test/teleport_test.go
> +	b, err = ioutil.ReadFile("./hosts")
This can be purged if we use `curl --resolve`.

2021-03-25 09:10 UTC, ysksuzuki commented on test/teleport_test.go
> +	b, err = ioutil.ReadFile("./hosts")
I though I could, but unfortunatelly `tsh` seems to require `/etc/hosts` entry.

2021-03-26 01:19 UTC, tapih approved these changes
LGTM

2021-03-26 01:19 UTC, merged