[skip ci] PoC for automated team management
cybozu-go/neco-apps pull request #1366
Opened 2021-04-05 01:24 UTC by yokaze

Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>

2021-04-14 01:33 UTC, yokaze commented on .circleci/config.yml
> +            - team-management/template/download
Merge two downloaded files into `/download`.

2021-04-14 01:35 UTC, yokaze commented on .gitignore
> +/team-management/template/download
Move to `/download`

2021-04-14 01:43 UTC, yokaze commented on team-management/template/Makefile
> +DOWNLOAD_DIR := $(abspath $(CURDIR)/download)
Move to `/download`

2021-04-14 01:46 UTC, yokaze commented on team-management/template/Makefile
> +	mv ../base/ept/elastic-serviceaccount.yaml /tmp/ept-elastic-serviceaccount.yaml
```
# Cleanup existing files
```

2021-04-14 01:47 UTC, yokaze commented on team-management/template/Makefile
> +team-management:
# Cleanup existing files

2021-04-14 01:52 UTC, yokaze commented on team-management/template/Makefile
> +	mv ../base/ept/elastic-serviceaccount.yaml /tmp/ept-elastic-serviceaccount.yaml
Generate `ServiceAccount` for all the teams and the namespaces.

2021-04-14 02:09 UTC, yokaze commented on team-management/template/team-management/base/team-template/kustomization.libsonnet
> +      if team == 'ept' || team == 'maneki' then ['elastic-serviceaccount.yaml'] else []
Provide `elastic-serviceaccount` for all teams.

2021-04-14 02:14 UTC, yokaze commented on team-management/template/team-management/base/team-template/namespace.libsonnet
> +      [if team == 'maneki' && namespace == 'maneki' then 'labels']: {
```
// This label may be unused.
```

2021-04-14 02:16 UTC, yokaze commented on team-management/template/team-management/base/team-template/namespace.libsonnet
> +      name: if team == 'maneki' && namespace == 'app-monitoring' then 'monitoring-role-binding' else team + '-role-binding',
Remove if branch.

2021-04-14 02:39 UTC, zoetrope requested changes
reviewed

2021-04-15 01:27 UTC, zoetrope approved these changes
LGTM

2021-04-15 01:28 UTC, merged