moco: deploy moco v0.8.1
cybozu-go/neco-apps pull request #1452
Opened 2021-05-07 05:20 UTC by yokaze

Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>

2021-05-07 05:29 UTC, ymmt2005 commented on Makefile
> +		https://github.com/cybozu-go/moco/releases/latest/download/moco.yaml
Download a tagged manifest.

2021-05-07 05:29 UTC, ymmt2005 commented on Makefile
>  	sed -i -E 's/newTag:.*$$/newTag: $(patsubst v%,%,$(latest_gh))/' moco/base/kustomization.yaml
We don't need to replace the image as MOCO is our product.

2021-05-07 05:31 UTC, ymmt2005 commented on moco/base/kustomization.yaml
> +apiVersion: kustomize.config.k8s.io/v1beta1
Why don't we use the upstream as is?

2021-05-07 05:33 UTC, ymmt2005 commented on test/testdata/moco.yaml
> +      accessModes: [ "ReadWriteOnce" ]
Use topolvm-provisioner.

2021-05-07 05:33 UTC, ymmt2005 commented on test/testdata/moco.yaml
> +            memory: "512Mi"
For tests, we don't need to give resource requests.

2021-05-07 05:34 UTC, ymmt2005 commented on test/testdata/moco.yaml
> +  namespace: test-moco
```suggestion
  namespace: sandbox
```

2021-05-07 05:34 UTC, ymmt2005 commented on test/moco_test.go
> +		createNamespaceIfNotExists("test-moco", false)
Let's use `sandbox`.

2021-05-07 06:39 UTC, ymmt2005 commented on test/moco_test.go
> +			stdout, _, err := ExecAt(boot0, "kubectl", "--namespace=test-moco", "get", "mysqlcluster/test", "-o", "jsonpath='{.status.ready}'")
Does `status.ready` really exist?
I don't think I implemented such a thing.

2021-05-07 06:40 UTC, ymmt2005 commented on test/moco_test.go
> +		stdout, stderr, err := ExecAt(boot0, "kubectl", "moco", "-n", "test-moco", "mysql", "-u", "root", "my-cluster", "--", "--version")
I don't think `root` user exists.  Please check the manual.

2021-05-07 06:51 UTC, yokaze commented on test/moco_test.go
> +			stdout, _, err := ExecAt(boot0, "kubectl", "--namespace=test-moco", "get", "mysqlcluster/test", "-o", "jsonpath='{.status.ready}'")
Currently the test code is same as that for MOCO v0.7.0, I'm just seeing the CI result and making fixes.

2021-05-07 06:53 UTC, ymmt2005 commented on test/moco_test.go
> +			stdout, _, err := ExecAt(boot0, "kubectl", "--namespace=test-moco", "get", "mysqlcluster/test", "-o", "jsonpath='{.status.ready}'")
Use this.

```console
$ kubectl -n foo get mysqlcluster/single -o jsonpath='{.status.conditions[?(@.type=="Healthy")].status}'
True
```

2021-05-10 04:46 UTC, yokaze commented
This PR should be merged with squash.

2021-05-10 09:55 UTC, ymmt2005 commented on test/testdata/moco.yaml
> +      affinity:
This cluster consists of 1 pod, so there is no need for (anti-)affinities.

2021-05-10 11:32 UTC, ymmt2005 commented on test/moco_test.go
> +				return fmt.Errorf("AvailableReplicas is not 2: %d", int(deployment.Status.AvailableReplicas))
int cast is not needed.

2021-05-10 11:34 UTC, ymmt2005 commented on test/moco_test.go
> +			stdout, _, err := ExecAt(boot0, "kubectl", "--namespace=sandbox", "get", "mysqlcluster/test", "-o", "{.status.conditions[?(@.type=='Healthy')].status}")
```suggestion
			stdout, _, err := ExecAt(boot0, "kubectl", "--namespace=sandbox", "get", "mysqlcluster/test", "--template", "{.status.conditions[?(@.type=='Healthy')].status}")
```

2021-05-10 11:38 UTC, ymmt2005 requested changes
Please fix.

2021-05-11 03:28 UTC, merged