[wip] add ceph-poc
cybozu-go/neco-apps pull request #1513
Opened 2021-05-24 03:00 UTC by toshipp

2021-06-04 06:40 UTC, llamerada-jp approved these changes
LGTM

2021-06-04 06:48 UTC, llamerada-jp submitted a review, later dismissed
LGTM after squash

2021-06-04 07:00 UTC, satoru-takeuchi requested changes

2021-06-04 07:08 UTC, toshipp commented on rook/overlays/gcp/kustomization.yaml
> +      value: 3Gi
I think it is a copy miss, but I can not find the requirement. Would you show me that?

2021-06-04 07:10 UTC, satoru-takeuchi commented on rook/overlays/gcp/kustomization.yaml
> +      value: 3Gi
OK, here it is.

https://docs.ceph.com/en/latest/cephadm/osd/
> The device must be larger than 5 GB.

2021-06-04 07:15 UTC, toshipp commented on rook/overlays/gcp/kustomization.yaml
> +      value: 3Gi
Thanks!
BTW, ceph says the osd is available even when the disk is lower than 5GB 🤔

2021-06-04 07:17 UTC, toshipp commented on rook/overlays/gcp/kustomization.yaml
> +      value: 3Gi
I'll squash a new commit.

2021-06-04 07:34 UTC, satoru-takeuchi commented on rook/overlays/gcp/kustomization.yaml
> +      value: 3Gi
Hmm, it's odd. IIRC, ceph-volume fails if the device is less than 5G.

I guess the reason is the difference between requested size written in PVC and the actual size of volume.  In our HDD cluster, PVC is always backed by whole device.

As for OSD on SSD, one possibility is that  topolvm creats at least 5GB volume or so. @llamerada-jp Do you know anything?

2021-06-04 07:45 UTC, satoru-takeuchi commented on rook/overlays/gcp/kustomization.yaml
> +      value: 3Gi
Anyway I believe the actual volume size >= 5G.

2021-06-07 01:34 UTC, llamerada-jp approved these changes
LGTM

2021-06-07 01:54 UTC, toshipp commented on rook/overlays/gcp/kustomization.yaml
> +      value: 3Gi
In my test environment, the size is actually 3GB and the odd pod works fine.

```
cybozu@gcp0-boot-0:~$ kubectl exec -it  -n ceph-poc  rook-ceph-osd-3-64f76c449b-dbqkw -- blockdev  --getsize64 /var/lib/ceph/osd/ceph-3/block
3221225472
cybozu@gcp0-boot-0:~$ kubectl get pod   -n ceph-poc  rook-ceph-osd-3-64f76c449b-dbqkw
NAME                               READY   STATUS    RESTARTS   AGE
rook-ceph-osd-3-64f76c449b-dbqkw   1/1     Running   0          41h
```

BTW, this is not related to this PR, would you accept this? If not, we can not merge this...

2021-06-07 02:02 UTC, satoru-takeuchi commented on rook/overlays/gcp/kustomization.yaml
> +      value: 3Gi
Sure.

2021-06-07 02:03 UTC, satoru-takeuchi approved these changes

2021-06-07 02:04 UTC, satoru-takeuchi commented
Please merge this PR after the integration test gets green.

2021-06-07 02:04 UTC, toshipp commented on rook/overlays/gcp/kustomization.yaml
> +      value: 3Gi
🙇

2021-06-07 02:06 UTC, merged