fix `auth_servers` in teleport.yaml
cybozu-go/neco-apps pull request #2048
Opened 2021-11-25 08:41 UTC by umezawatakeshi

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

2021-11-25 08:55 UTC, yokaze approved these changes
LGTM

2021-11-25 09:47 UTC, zoetrope approved these changes

2021-12-02 02:43 UTC, morimoto-cybozu requested changes

2021-12-02 02:43 UTC, morimoto-cybozu commented on teleport/base/deployment.yaml
> +apiVersion: policy/v1beta1
```suggestion
apiVersion: policy/v1
```

2021-12-02 02:50 UTC, kmdkuk commented
LGTM

2021-12-02 07:10 UTC, morimoto-cybozu approved these changes
LGTM

2021-12-02 08:50 UTC, merged