namespaces: change team label of namespaces managed by CSA
cybozu-go/neco-apps pull request #2083
Opened 2021-12-06 07:11 UTC by daichimukai

issue: cybozu/csa#81

2021-12-10 09:54 UTC, yokaze requested changes

2021-12-10 09:54 UTC, yokaze commented on rook/base/ceph-hdd/namespace.yaml
> +    argocd.argoproj.io/sync-wave: "-1"
Unlike SubNamespaces, Namespaces are prioritized by Argo CD automatically.

```suggestion
```

2021-12-10 09:54 UTC, yokaze commented on rook/base/ceph-object-store/namespace.yaml
> +    argocd.argoproj.io/sync-wave: "-1"
ditto
```suggestion
```

2021-12-10 09:54 UTC, yokaze commented on rook/base/ceph-ssd/namespace.yaml
> +    argocd.argoproj.io/sync-wave: "-1"
ditto
```suggestion
```

2021-12-10 09:54 UTC, yokaze commented on rook/poc/ceph-poc-2/namespace.yaml
> +    argocd.argoproj.io/sync-wave: "-1"
ditto
```suggestion
```

2021-12-10 09:54 UTC, yokaze commented on rook/poc/ceph-poc/namespace.yaml
> +    argocd.argoproj.io/sync-wave: "-1"
ditto
```suggestion
```

2021-12-10 09:54 UTC, yokaze commented on test/setup_test.go
> +func getRevisionOfApplication(appName string) string {
I prefer to use `getApplicationRevision`.

```suggestion
func getApplicationRevision(appName string) string {
```

2021-12-13 01:29 UTC, daichimukai commented on rook/base/ceph-hdd/namespace.yaml
> +    argocd.argoproj.io/sync-wave: "-1"
This namespaces hold config map with sync-wave: -1, so this annotation is necessary.

https://github.com/cybozu-go/neco-apps/blob/551b89abc21ec16a6f191eee54cb6fd3c65cb79d/rook/base/ceph-hdd/configmap.yaml#L5-L7

2021-12-13 07:44 UTC, daichimukai commented on test/setup_test.go
> +func getRevisionOfApplication(appName string) string {
Renamed.

2021-12-14 04:19 UTC, yokaze approved these changes
LGTM

2021-12-15 00:38 UTC, merged