Add a dashboard of CSA Overview
cybozu-go/neco-apps pull request #2091
Opened 2021-12-08 08:06 UTC by llamerada-jp

Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>

2021-12-13 08:56 UTC, toshipp requested changes

2021-12-13 08:56 UTC, toshipp commented on monitoring/base/grafana-operator/dashboards/csa-overview.yaml
> +              "instant": false,
I tested with the field set to true, it provides a more readable result.
![image](https://user-images.githubusercontent.com/2258537/145781364-a0bfc9ed-5f2f-4adb-a548-986576fd4197.png)

2021-12-14 00:51 UTC, llamerada-jp commented on monitoring/base/grafana-operator/dashboards/csa-overview.yaml
> +              "instant": false,
I updated the view like below.
![image](https://user-images.githubusercontent.com/2675889/145912559-9570efd4-0d6f-426f-baa7-7709e9dedf6b.png)

2021-12-14 00:59 UTC, toshipp approved these changes
LGTM

2021-12-15 00:37 UTC, merged