./add_team.sh set && make all
cybozu-go/neco-apps pull request #2161
Opened 2022-01-07 02:25 UTC by kmdkuk

Signed-off-by: kouki <kouworld0123@gmail.com>

2022-01-07 05:17 UTC, zoetrope requested changes
You have to remove teleport-node on prod in the same way as set-cloud-platform.
https://github.com/cybozu-go/neco-apps/blob/a3a465576256b3dcba9c80117126ec2d2596867e/teleport/overlays/tokyo0/node-set-cloud-platform.yaml

2022-01-11 06:02 UTC, morimoto-cybozu approved these changes
LGTM

2022-01-11 07:13 UTC, zoetrope approved these changes
LGTM

2022-01-11 12:38 UTC, yokaze approved these changes

2022-01-12 01:08 UTC, merged