Fix false NodeUnreachable alerts.
cybozu-go/neco-apps pull request #2205
Opened 2022-01-24 08:00 UTC by kmdkuk

Signed-off-by: kouki <kouworld0123@gmail.com>

2022-01-24 08:18 UTC, yokaze requested changes
Could you please include the instance or address in the message?

2022-01-24 08:57 UTC, kmdkuk commented
@yokaze 
Thank you for your comment.
I have modified the summary to show the address and serial that might be used by commands such as `sabactl`.

2022-01-24 09:30 UTC, yokaze requested changes

2022-01-24 09:38 UTC, morimoto-cybozu commented on monitoring/base/victoriametrics/rules/sabakan-alertrule.yaml
> +            sum by(instance, address, serial) (sabakan_machine_status{status="unreachable"}) > 0
"instance" is the address of the data source, i.e. the boot server.
I'm not sure whether it is reasonable to sum by "instance."

2022-01-26 04:13 UTC, kmdkuk commented on monitoring/base/victoriametrics/rules/sabakan-alertrule.yaml
> +            sum by(instance, address, serial) (sabakan_machine_status{status="unreachable"}) > 0
Thank you. I think you're right on point.
Currently, there are three instance labels for each address and serial, but the status is synchronized.
Therefore, if an unreachable node appeared, three alerts would be issued when the instance label was split.
I fixed it so that it only sums up the address and serial.

2022-01-26 04:28 UTC, morimoto-cybozu approved these changes
LGTM

2022-01-27 02:27 UTC, yokaze approved these changes
LGTM

2022-01-27 06:22 UTC, merged