Fixes retired boot servers so that they do not trigger alerts.
cybozu-go/neco-apps pull request #2215
Opened 2022-01-27 06:29 UTC by kmdkuk

Signed-off-by: kouki <kouworld0123@gmail.com>

2022-01-28 05:12 UTC, masa213f commented on monitoring/base/victoriametrics/rules/sabakan-alertrule.yaml
> +            sum(sabakan_machine_status{status!="healthy", status!="retired", role="boot"}) > 0
Why don't you exclude retiring?

```suggestion
            sum(sabakan_machine_status{status!~"healthy|retiring|retired", role="boot"}) > 0
```

2022-01-28 05:36 UTC, kmdkuk commented on monitoring/base/victoriametrics/rules/sabakan-alertrule.yaml
> +            sum(sabakan_machine_status{status!="healthy", status!="retired", role="boot"}) > 0
I've communicated elsewhere, but I'm writing this for the record.
Since retiring is originally expected to automatically transition to retired, I thought it was an anomaly for the retiring state to continue.
The use of regular expressions to get metrics has been reflected.

2022-01-28 05:43 UTC, masa213f approved these changes
LGTM

2022-01-28 05:52 UTC, morimoto-cybozu requested changes

2022-01-28 05:52 UTC, morimoto-cybozu commented on test/vmalert_test/sabakan.yaml
> +        exp_alerts: []
This test case should be merged into the previous one.

2022-02-01 07:16 UTC, morimoto-cybozu commented on test/vmalert_test/sabakan.yaml
> +        exp_alerts: []
I withdraw the previous comment.
The alert expression uses `sum` without preserving dimensions, and we cannot test multiple cases in one set of input_series.

Instead I propose two discrete modifications.
1. Remove the new test case.  We originally do not test all cases.  We do not confirm that the alert is not issued if a boot server is healthy.
2. Use `by(address, serial)` in the alert expression as we do in the `NodeUnreachable` alert.  This would go beyond this PR.

2022-02-01 08:14 UTC, masa213f approved these changes
LGTM

2022-02-01 09:01 UTC, morimoto-cybozu approved these changes

2022-02-01 09:02 UTC, merged