rook/ceph: add regeneration safety
cybozu-go/neco-apps pull request #2289
Opened 2022-02-18 06:17 UTC by llamerada-jp

Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>

2022-02-21 00:41 UTC, toshipp commented on .circleci/config.yml
> +            if [ "$diffs" != "" ]; then printf "%s\n" "$diffs"; exit 1; fi
Why don't you use `git diff --exit-code` instead?

2022-02-21 00:43 UTC, toshipp requested changes

2022-02-21 00:43 UTC, toshipp commented on .circleci/config.yml
> +            if [ "$diffs" != "" ]; then printf "%s\n" "$diffs"; exit 1; fi
Why don't you use `git diff --exit-code` instead?

2022-02-22 08:55 UTC, llamerada-jp commented on .circleci/config.yml
> +            if [ "$diffs" != "" ]; then printf "%s\n" "$diffs"; exit 1; fi
refrected it

2022-02-22 09:06 UTC, toshipp submitted a review, later dismissed

2022-02-22 09:07 UTC, toshipp commented
@cupnes If you have no objection, please merge this.

2022-02-28 05:27 UTC, cupnes approved these changes

2022-02-28 05:27 UTC, merged