remove old sandbox Grafana
cybozu-go/neco-apps pull request #2290
Opened 2022-02-18 06:53 UTC by umezawatakeshi

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

2022-02-22 00:34 UTC, masa213f requested changes
Please remove this update command.
https://github.com/cybozu-go/neco-apps/blob/4b20cac5a2c1ed4c5e7bc6ef6ee8a68cd892e548/Makefile#L104

2022-02-22 00:34 UTC, masa213f commented on sandbox/overlays/gcp/dummy-configmap.yaml
> +apiVersion: v1
Is this dummy resource necessary?
The sandbox applications on tokyo0 and osaka0 are empty.
So I guess, it can be empty on gcp and stage0 as well.

2022-02-22 06:40 UTC, umezawatakeshi commented on sandbox/overlays/gcp/dummy-configmap.yaml
> +apiVersion: v1
When an app become empty, `argocd app sync --prune` is required. I don't like to do so each time.

If we decide not to modify sandbox NS anymore, explicit prune may be acceptable.

2022-03-14 01:10 UTC, masa213f approved these changes

2022-03-17 05:37 UTC, merged