rook: Change mon_osd_down_out_subtree_limit
cybozu-go/neco-apps pull request #2316
Opened 2022-02-28 05:21 UTC by cupnes

issue: https://github.com/cybozu/csa/issues/19

Signed-off-by: Yuma Ogami <yuma-ogami@cybozu.co.jp>

2022-02-28 08:15 UTC, llamerada-jp requested changes
Could you please modity the ConfigMap on `rook/overlays/gcp/ceph-object-store/debug.yaml`?

2022-02-28 11:35 UTC, peng225 submitted a review, later dismissed

2022-03-01 01:27 UTC, llamerada-jp approved these changes

2022-03-01 08:04 UTC, peng225 approved these changes

2022-03-01 08:05 UTC, merged