delete app-csa-privileged NS
cybozu-go/neco-apps pull request #2414
Opened 2022-03-24 08:40 UTC by umezawatakeshi

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

2022-03-24 09:12 UTC, morimoto-cybozu requested changes

2022-03-24 09:12 UTC, morimoto-cybozu commented on test/setup_test.go
> +			stdout, stderr, err := ExecAt(boot0, "kubectl", "annotate", "ns", "dev-kintone", "admission.cybozu.com/i-am-sure-to-delete=app-csa-privileged")
```suggestion
			stdout, stderr, err := ExecAt(boot0, "kubectl", "annotate", "ns", "app-csa-privileged", "admission.cybozu.com/i-am-sure-to-delete=app-csa-privileged")
```

2022-03-24 09:27 UTC, umezawatakeshi commented on test/setup_test.go
> +			stdout, stderr, err := ExecAt(boot0, "kubectl", "annotate", "ns", "dev-kintone", "admission.cybozu.com/i-am-sure-to-delete=app-csa-privileged")
oops...

2022-03-24 09:39 UTC, morimoto-cybozu submitted a review, later dismissed
LGTM
Great utility!
We'll need `var _ = annotateNamespaceToDeleteDuringUpgrade` when deleting the caller.

2022-03-25 09:19 UTC, morimoto-cybozu approved these changes
LGTM

2022-03-25 09:20 UTC, merged