Update sealed-secrets
cybozu-go/neco-apps pull request #2509
Opened 2022-04-20 09:06 UTC by masa213f

Signed-off-by: Masayuki Ishii <masa213f@gmail.com>

2022-04-28 04:18 UTC, yokaze submitted a review, later dismissed
LGTM

2022-05-09 05:42 UTC, yokaze requested changes
I suspect rebasing is cleaner than merging. Could you modify the branch?

2022-05-09 06:27 UTC, masa213f commented
@yokaze 
That's true! I rebased this branch.

2022-05-09 06:30 UTC, yokaze approved these changes
LGTM 🙇‍♂️

2022-05-09 08:10 UTC, merged