Add office team
cybozu-go/neco-apps pull request #2583
Opened 2022-05-11 02:49 UTC by zoetrope

Signed-off-by: zoetrope <a.ikezoe@gmail.com>

2022-05-11 08:37 UTC, umezawatakeshi approved these changes

2022-05-11 12:14 UTC, morimoto-cybozu commented
@zoetrope 
I cannot see what you did.
Would you please tell me what commands you executed and which document you followed?

2022-05-12 01:09 UTC, zoetrope commented
https://github.com/cybozu-private/neco-wiki/pull/678

2022-05-12 09:38 UTC, morimoto-cybozu requested changes

2022-05-12 09:38 UTC, morimoto-cybozu commented on team-management/template/settings.json
> +      ],
This block is not described in the procedure document.
Not all Neco members could supply this block just by reading the document and the request record.
The document should be enhanced.

2022-05-12 09:38 UTC, morimoto-cybozu commented on team-management/template/settings.json
> +          "https://github.com/cybozu-private/*"
This URL pattern represents a wider range of repositories than requested.
Not all Neco members could put this pattern just by reading the document and the request record.
The document should be enhanced.

2022-05-12 10:31 UTC, zoetrope commented on team-management/template/settings.json
> +      ],
added: https://github.com/cybozu-private/neco-wiki/pull/680

2022-05-12 10:31 UTC, zoetrope commented on team-management/template/settings.json
> +          "https://github.com/cybozu-private/*"
added: https://github.com/cybozu-private/neco-wiki/pull/680

2022-05-12 10:33 UTC, morimoto-cybozu approved these changes
LGTM

2022-05-12 10:33 UTC, merged