namespaces: migrate some namespace resouces to namesapces application
cybozu-go/neco-apps pull request #2585
Opened 2022-05-11 07:05 UTC by daichimukai

2022-05-11 07:18 UTC, toshipp requested changes

2022-05-11 07:18 UTC, toshipp commented on namespaces/overlays/stage0/csa/kustomization.yaml
> +  - rook.yaml
add commonLabels for the team label.

2022-05-12 01:25 UTC, toshipp submitted a review, later dismissed

2022-05-12 06:36 UTC, cupnes submitted a review, later dismissed

2022-05-17 01:02 UTC, toshipp approved these changes

2022-05-17 01:02 UTC, merged