rook: Update to 1.4.2 using raw mode.
cybozu-go/neco-apps pull request #737
Opened 2020-09-10 05:46 UTC by kfyharukz

Signed-off-by: Kazuhito MATSUDA <kazuhito.matuda@gmail.com>

2020-09-17 02:48 UTC, morimoto-cybozu requested changes

2020-09-17 02:48 UTC, morimoto-cybozu commented on test/setup_test.go
> +	// Please delete this block after Rook 1.4 is applied
Use "TODO:" for ease of search.
```suggestion
	// TODO: delete this block after Rook 1.4 is applied
```

2020-09-17 02:48 UTC, morimoto-cybozu commented on test/setup_test.go
>  	// want to do "Eventually( Consistently(checkAllAppsSynced, 30sec, 1sec) )"
Update this comment too.
I'm not sure if the duration of 15 seconds is long enough to examine the stability.  The original setting of 30 seconds did not have a concrete reason, though.

```suggestion
	// want to do "Eventually( Consistently(checkAllAppsSynced, 15sec, 1sec) )"
```

2020-09-17 02:48 UTC, morimoto-cybozu commented on docs/maintenance.md
> +Read [this document](https://github.com/rook/rook/blob/master/Documentation/ceph-upgrade.md) before. Note that you should choose the appropriate release version.
```suggestion
Read [this document](https://github.com/rook/rook/blob/master/Documentation/ceph-upgrade.md) first. Note that you should choose the appropriate release version.
```

2020-09-17 02:52 UTC, kfyharukz commented on test/setup_test.go
>  	// want to do "Eventually( Consistently(checkAllAppsSynced, 30sec, 1sec) )"
The command `argocd app get` itself takes 1 or 2 sec, so actually this process consumes a long time (e.g., over 10 min).  I think it is enough time to confirm convergence.

2020-09-17 04:04 UTC, morimoto-cybozu approved these changes
LGTM

2020-09-17 07:32 UTC, satoru-takeuchi submitted a review, later dismissed

2020-10-08 02:19 UTC, morimoto-cybozu approved these changes
LGTM

2020-10-08 02:32 UTC, merged