rook: bump rook version to 1.4.6
cybozu-go/neco-apps pull request #789
Opened 2020-10-20 02:03 UTC by llamerada-jp

Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>

2020-11-02 02:40 UTC, toshipp commented
@kfyharukz @satoru-takeuchi 
All tests passed, would you review this?

2020-11-04 01:44 UTC, kfyharukz commented on test/storage_test.go
> +		It("should rook's Deployments version of "+ns+" is equal to operators version", func() {
I think you'd better use `By` sentences to show what you intend the codes.

2020-11-04 01:52 UTC, kfyharukz requested changes

2020-11-04 01:52 UTC, kfyharukz commented on test/storage_test.go
> +		It("should rook's Deployments version of "+ns+" is equal to operators version", func() {
I think this test name isn't appropriate because this test includes a health check of the `Deployments` and the ceph cluster.  
And, you'd better use `By` sentences to show what you intend with the codes.

2020-11-05 07:51 UTC, kfyharukz approved these changes
LGTM

2020-11-05 07:51 UTC, merged