customer-egress: Add squid for customers.
cybozu-go/neco-apps pull request #829
Opened 2020-11-17 08:08 UTC by kfyharukz

Signed-off-by: Kazuhito MATSUDA <kazuhito.matuda@gmail.com>

2020-11-18 12:23 UTC, morimoto-cybozu approved these changes
LGTM

2020-11-19 02:07 UTC, ymmt2005 requested changes

2020-11-19 02:07 UTC, ymmt2005 commented on customer-egress/base/namespace.yaml
> +    control-plane: "true"
add `team: neco`
https://github.com/cybozu-go/neco-apps/blob/master/namespaces/base/kustomization.yaml#L19-L20

2020-11-19 02:07 UTC, ymmt2005 commented on customer-egress/base/neco/squid.yaml
> +  namespace: internet-egress
customer-egress?

2020-11-19 02:07 UTC, ymmt2005 commented on customer-egress/base/kustomization.yaml
> +namespace: customer-egress
I don't think this is a good idea.
IMO, `namespace` stanza should only be used to fill in resources with missing namespace field.

2020-11-19 02:08 UTC, ymmt2005 commented
@kfyharukz Please resolve the conflict too.

2020-11-19 03:00 UTC, kfyharukz commented on customer-egress/base/kustomization.yaml
> +namespace: customer-egress
I see.  I've changed the maintenance way.
https://github.com/cybozu-go/neco-apps/pull/829/files#diff-0541ee302f10469f3b0290ea7585f45ff9652bc6de7131548819836586da0eb3R308

2020-11-19 04:07 UTC, ymmt2005 submitted a review, later dismissed
LGTM

2020-11-20 02:43 UTC, ymmt2005 approved these changes
LGTM

2020-11-20 02:44 UTC, merged