add VictoriaMetrics operator
cybozu-go/neco-apps pull request #850
Opened 2020-11-25 06:24 UTC by umezawatakeshi

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

2020-12-07 02:29 UTC, morimoto-cybozu commented on test/monitoring_test.go
> +				return fmt.Errorf("unable to curl :9090/-/halthy, stderr: %s, err: %v", stderr, err)
```suggestion
				return fmt.Errorf("unable to curl :9093/-/halthy, stderr: %s, err: %v", stderr, err)
```

2020-12-07 02:41 UTC, morimoto-cybozu commented on monitoring/base/victoriametrics/vmagent-smallset.yaml
> +  replicaCount: 2
It would be nice if we can dedupe incoming data.

2020-12-07 07:28 UTC, morimoto-cybozu commented on test/Makefile
> +test-promalert-rules:
Update ".PHONY" too.
You can place each ".PHONY" definition near its corresponding recipe.

2020-12-07 07:34 UTC, masa213f commented on docs/maintenance.md
> +```
Please add a note to update the image tags in some CRs.

2020-12-07 08:22 UTC, morimoto-cybozu commented on test/validation_test.go
> +	const vmBaseDir = manifestDir + "monitoring/base/victoriametrics"
```suggestion
	vmBaseDir := filepath.Join(manifestDir, "monitoring", "base", "victoriametrics")
```

`filepath.Join(manifestDir, "monitoring/base/victoriametrics")` is acceptable for me though it would be less portable.
Aside from portability, `filepath.Join()` allows us not to be worried about leading/trailing slashes as used in `dirPath + "/file"`.

2020-12-07 08:30 UTC, morimoto-cybozu commented on test/validation_test.go
> +			break
This `break` should be removed if you want to read multiple `VMAlert`s.

2020-12-07 08:38 UTC, masa213f requested changes

2020-12-08 07:35 UTC, morimoto-cybozu commented on test/validation_test.go
> +	vmBaseDir := filepath.Join(manifestDir, "monitoring/base/victoriametrics")
Fix other two concatenations in this source file as well.

```
        file, err := os.Open(vmBaseDir + "/vmagent-smallset.yaml")
```

```
        file, err = os.Open(vmBaseDir + "/vmalert-smallset.yaml")
```

2020-12-08 07:57 UTC, masa213f approved these changes
LGTM

2020-12-08 07:59 UTC, morimoto-cybozu commented on test/validation_test.go
> +	file, err := os.Open(filepath.Join(vmBaseDir, "/vmagent-smallset.yaml"))
No need to place "/" explicitly.

2020-12-09 07:38 UTC, masa213f submitted a review, later dismissed
LGTM

2020-12-09 09:22 UTC, morimoto-cybozu approved these changes
LGTM

2020-12-09 09:32 UTC, merged