test: Validate namespace labels
cybozu-go/neco-apps pull request #895
Opened 2020-12-08 02:56 UTC by masa213f

Signed-off-by: Masayuki Ishii <masa213f@gmail.com>

2020-12-08 08:43 UTC, morimoto-cybozu requested changes

2020-12-08 08:43 UTC, morimoto-cybozu commented on test/validation_test.go
> +				t.Error(fmt.Errorf("kustomize build faled. path: %s, stderr: %s, err: %v", targetDir, stderr, err))
```suggestion
				t.Error(fmt.Errorf("kustomize build failed. path: %s, stderr: %s, err: %v", targetDir, stderr, err))
```

2020-12-08 08:43 UTC, morimoto-cybozu commented on test/validation_test.go
> +					t.Error(err)
```suggestion
					t.Fatal(err)
```

You cannot rely on `data` any more.

2020-12-08 08:43 UTC, morimoto-cybozu commented on test/validation_test.go
> +					t.Error(err)
```suggestion
					t.Fatal(err)
```

2020-12-08 08:43 UTC, morimoto-cybozu commented on test/validation_test.go
> +						t.Error(fmt.Errorf("sandbox ns have team label: value=%s", meta.Labels["team"]))
```suggestion
						t.Errorf("sandbox ns has team label: value=%s", meta.Labels["team"])
```

2020-12-08 08:43 UTC, morimoto-cybozu commented on test/validation_test.go
> +					t.Error(fmt.Errorf("%s ns doesn't have team label", meta.Name))
```suggestion
					t.Errorf("%s ns doesn't have team label", meta.Name)
```

2020-12-08 08:43 UTC, morimoto-cybozu commented on test/validation_test.go
> +		"team-management": filepath.Join(manifestDir, "team-management", "base"),
IIRC we recently changed the policy for the placement of Namespace manifests.
New Namespace manifests will be placed in their applications' directories, like "moco/base/namespace.yaml."

Can you list all application directories dynamically?

2020-12-09 03:58 UTC, morimoto-cybozu requested changes

2020-12-09 03:58 UTC, morimoto-cybozu commented on test/validation_test.go
> +			if meta.Labels["team"] != "" {
```suggestion
			if _, ok := meta.Labels["team"]; ok {
```

My modified check rejects the label of `team: ""`.
Though this type of label may cause no harm, it heavily depends on the context.
So I prefer strict check.

2020-12-09 03:58 UTC, morimoto-cybozu commented on test/validation_test.go
> +				t.Errorf("sandbox ns have team label: value=%s", meta.Labels["team"])
```suggestion
				t.Errorf("sandbox ns has team label: value=%s", meta.Labels["team"])
```

2020-12-09 03:58 UTC, morimoto-cybozu commented on test/validation_test.go
> +		if meta.Labels["team"] == "" {
This check is OK because `team: ""` is clearly invalid as well as no team label for the other namespaces.

2020-12-09 03:58 UTC, morimoto-cybozu commented on test/validation_test.go
> +		t.Errorf("namespaces in AppProjects are not listed correctly\nnamespacesByTeam: %s\nnamespacesInAppProject: %s", namespacesByTeam, namespacesInAppProject)
`cmp.Diff()` produces a readable diff.
`cmp.Equal()` is also usable.
https://godoc.org/github.com/google/go-cmp/cmp

2020-12-09 03:58 UTC, morimoto-cybozu commented on test/validation_test.go
> +		}
Just a matter of taste.

```
  switch meta.Kind {
  case "Namespace":
    ...
    continue
  case "AppProject":
  default:
    continue
  }
```

2020-12-09 08:32 UTC, umezawatakeshi reviewed
LGTM

2020-12-09 08:52 UTC, masa213f commented
@morimoto-cybozu

2020-12-09 08:54 UTC, masa213f commented
@morimoto-cybozu 
I fixed the comments. Please review.

2020-12-09 10:12 UTC, morimoto-cybozu submitted a review, later dismissed
LGTM

2020-12-10 01:14 UTC, morimoto-cybozu approved these changes
LGTM

2020-12-10 01:15 UTC, merged