monitoring: fix alert rules to use neco reboot-worker
cybozu-go/neco-apps pull request #900
Opened 2020-12-08 08:28 UTC by yokaze

Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>

2020-12-08 13:45 UTC, masa213f requested changes

2020-12-08 13:45 UTC, masa213f commented on monitoring/base/prometheus/alert_rules/cke.yaml
> +          sum(rate(cke_sabakan_integration_timestamp_seconds[5m])) == 0 and sum(cke_operation_phase{phase="reboot-nodes"}) == 0
How about this?
```
((cke_sabakan_integration_timestamp_seconds - cke_sabakan_integration_timestamp_seconds offset 5m) == 0)
  and ignoring(phase)
(cke_operation_phase{phase="reboot-nodes"} == 0)
```
or
```
((cke_sabakan_integration_timestamp_seconds - cke_sabakan_integration_timestamp_seconds offset 5m) == 0)
  unless ignoring(phase)
(cke_operation_phase{phase="reboot-nodes"} == 1)
```
The result has `instance` label. We can improve the messages which will be posted in slack.

2020-12-08 13:45 UTC, masa213f commented on monitoring/base/prometheus/alert_rules/kubernetes.yaml
> +          sum by(node) (kube_node_status_condition{job="kube-state-metrics",condition="Ready",status="true"}) == 0 and sum by(node) (kube_node_spec_unschedulable{job="kube-state-metrics"}) == 0
How about this?
```
(kube_node_status_condition{job="kube-state-metrics",condition="Ready",status="true"} == 0)
  and ignoring(condition, status)
(kube_node_spec_unschedulable{job="kube-state-metrics"} == 0)
```

or 
```
(kube_node_status_condition{job="kube-state-metrics",condition="Ready",status="true"} == 0)
  unless ignoring(condition, status)
(kube_node_spec_unschedulable{job="kube-state-metrics"} == 1)
```

2020-12-09 02:34 UTC, yokaze commented on monitoring/base/prometheus/alert_rules/cke.yaml
> +          sum(rate(cke_sabakan_integration_timestamp_seconds[5m])) == 0 and sum(cke_operation_phase{phase="reboot-nodes"}) == 0
When we use `ignoring` with two different metrics, we need to know the complete set of labels in advance. It seems a bit difficult.
Phrases like `sum by` can keep necessary labels without knowing them exactly, hence it may improve readability.
How do you think?

2020-12-09 02:50 UTC, masa213f commented on monitoring/base/prometheus/alert_rules/cke.yaml
> +          sum(rate(cke_sabakan_integration_timestamp_seconds[5m])) == 0 and sum(cke_operation_phase{phase="reboot-nodes"}) == 0
> It seems a bit difficult.

We need to know the labels to write a proper rule, I think. Is it difficult?

- `cke_sabakan_integration_timestamp_seconds` has only 2 labels. (`job` and `instance` labels)
- `cke_operation_phase` has only 3 labels. (`job`, `instance` and ` phase` labels)

With Grafana it's easy to see.

Also, I don't understand the intent of summarizing metrics by sum or max.

2020-12-09 02:52 UTC, yokaze commented on monitoring/base/prometheus/alert_rules/cke.yaml
> +          sum(rate(cke_sabakan_integration_timestamp_seconds[5m])) == 0 and sum(cke_operation_phase{phase="reboot-nodes"}) == 0
ic, I'll fix the expression as you wrote. Thanks for the comment.

2020-12-09 05:26 UTC, yokaze commented
This PR should be merged with squash.

2020-12-09 07:11 UTC, masa213f approved these changes

2020-12-09 07:11 UTC, merged